### ISSUE TITLE
Toast notifications

### ISSUE THREAD

**Issue by arcstur** [WikiMovimentoBrasil/quickstatements3#50]
Maybe we can use django's built-in messages framework together with this JS library: https://apvarun.github.io/toastify-js/ or this one: https://carlosroso.com/notyf/

**Comment by deviserops** [comment]
Hi @arcstur 

If you are looking for simple and extreme lightweight you can try this: https://www.npmjs.com/package/@deviser/notify

**Comment by arcstur** [comment]
I was reviewing the code and the UI again, and I don't think we need toast notifications for now :)
