### ISSUE TITLE
Create button/filter to show only errors on batch commands list view

### ISSUE THREAD

**Issue by arcstur** [WikiMovimentoBrasil/quickstatements3#83]

**Comment by kemsguy7** [comment]
@arcstur would you mind throwing more light into this issue, and could you please assign it to me?

**Comment by arcstur** [comment]
> @arcstur would you mind throwing more light into this issue, and could you please assign it to me?

Are you an Outreachy participant? If so, please read the documentation [there](https://phabricator.wikimedia.org/T376128) on how to apply for the project.
